HTM-1951: Guard for NPE on GeoServiceSettings.getLayerSettings()
According to the models this should not be possible, reality is different....

```
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "org.tailormap.api.persistence.json.GeoServiceSettings.getLayerSettings()" is null
        at org.tailormap.api.security.AuthorisationService.userAllowedToViewGeoServiceLayer(AuthorisationService.java:216) ~[classes/:12.6.0]
        at org.tailormap.api.persistence.helper.ApplicationHelper$MapResponseLayerBuilder.findServiceLayer(ApplicationHelper.java:511) ~[classes/:12.6.0]
        at org.tailormap.api.persistence.helper.ApplicationHelper$MapResponseLayerBuilder.addAppLayerItem(ApplicationHelper.java:337) ~[classes/:12.6.0]
        at org.tailormap.api.persistence.helper.ApplicationHelper$MapResponseLayerBuilder.addAppTreeNodeItem(ApplicationHelper.java:317) ~[classes/:12.6.0]
        at org.tailormap.api.persistence.helper.ApplicationHelper$MapResponseLayerBuilder.buildOverlayLayers(ApplicationHelper.java:249) ~[classes/:12.6.0]
        at org.tailormap.api.persistence.helper.ApplicationHelper$MapResponseLayerBuilder.buildLayers(ApplicationHelper.java:227) ~[classes/:12.6.0]
        at org.tailormap.api.persistence.helper.ApplicationHelper.setLayers(ApplicationHelper.java:163) ~[classes/:12.6.0]
        at org.tailormap.api.persistence.helper.ApplicationHelper.toMapResponse(ApplicationHelper.java:138) ~[classes/:12.6.0]
```