Revert "Bump jackson-bom.version from 3.1.4 to 3.2.0"
because:

org.springframework.dao.InvalidDataAccessApiUsageException: Could not serialize object of java type: class org.tailormap.api.persistence.json.AppContent
...
Caused by: java.lang.IllegalArgumentException: Could not serialize object of java type: class org.tailormap.api.persistence.json.AppContent
...
Caused by: tools.jackson.databind.exc.InvalidDefinitionException: Conflict between type id property 'objectType' and bean property with same name; consider using `JsonTypeInfo.As.EXISTING_PROPERTY` to avoid duplication
 at [No location information] (through reference chain: org.tailormap.api.persistence.json.AppContent["baseLayerNodes"]->java.util.ArrayList[0])